# Generated by Django 3.2.16 on 2022-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='About Our Fruit Shop', max_length=100, verbose_name='Titulo')),
                ('descripcion', models.TextField(default='There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour', max_length=1000, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='images/shop/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'about',
                'verbose_name_plural': '5- Sección About',
            },
        ),
        migrations.CreateModel(
            name='carrusel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='images/carrusel1/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'elemento',
                'verbose_name_plural': '2- Carrusel 1',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Request A call back', max_length=100, verbose_name='Título')),
                ('mapa', models.CharField(default='', max_length=200, verbose_name='Nombre del cliente')),
            ],
            options={
                'verbose_name': 'Contáctenos',
                'verbose_name_plural': '10- Contáctenos',
            },
        ),
        migrations.CreateModel(
            name='fruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='images/fruit/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'fruta',
                'verbose_name_plural': '7- Frutas',
            },
        ),
        migrations.CreateModel(
            name='fruitTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Fresh Fruit', max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'título para fruta',
                'verbose_name_plural': '6- Título para frutas',
            },
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubicacion', models.CharField(default='', max_length=100, verbose_name='Unicacion')),
                ('telef', models.CharField(max_length=100, verbose_name='Unicacion')),
                ('email', models.EmailField(default='', max_length=100, verbose_name='Mail')),
                ('facebook', models.CharField(default='', max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(default='', max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(default='', max_length=100, verbose_name='Instagram')),
                ('linkedin', models.CharField(default='', max_length=100, verbose_name='Linkedin')),
            ],
            options={
                'verbose_name': 'información',
                'verbose_name_plural': '11- Informaciones',
            },
        ),
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(default='Home', max_length=100, verbose_name='Home')),
                ('about', models.CharField(default='About', max_length=100, verbose_name='About')),
                ('fruit', models.CharField(default='Our Fruit', max_length=100, verbose_name='Fruit')),
                ('testimonial', models.CharField(default='Testimonial', max_length=100, verbose_name='Testimonial')),
                ('contact', models.CharField(default='Contact Us', max_length=100, verbose_name='Contact')),
            ],
            options={
                'verbose_name': 'elemento',
                'verbose_name_plural': '3- Barra de navegación',
            },
        ),
        migrations.CreateModel(
            name='shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Fruit shop', max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(default='There are many variations of passages of Lorem Ipsum available', max_length=1000, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='images/fruit/', verbose_name='Imagen')),
                ('boton', models.CharField(default='Buy now', max_length=1000, verbose_name='Botón')),
            ],
            options={
                'verbose_name': 'shop',
                'verbose_name_plural': '4- Shop',
            },
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCliente', models.CharField(default='', max_length=100, verbose_name='Nombre del cliente')),
                ('descripcion', models.TextField(default='', max_length=1000, verbose_name='Descripcion')),
                ('imagen', models.ImageField(upload_to='images/fruit/', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'testimonio',
                'verbose_name_plural': '9- Testimonios',
            },
        ),
        migrations.CreateModel(
            name='testimonialTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='What Syas Cutomer', max_length=100, verbose_name='Nombre del cliente')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': '8- Título para testimonios',
            },
        ),
        migrations.CreateModel(
            name='titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'titulo',
                'verbose_name_plural': '1- Título',
            },
        ),
    ]
