# Generated by Django 3.2.16 on 2022-12-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_info_telef'),
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('mensaje', models.TextField(max_length=1000, verbose_name='Mensaje')),
                ('numero', models.CharField(max_length=100, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Nuestro Equipo',
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='mapa',
            field=models.CharField(default='', max_length=200, verbose_name='Mapa'),
        ),
        migrations.AlterField(
            model_name='info',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='info',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='info',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Linkedin'),
        ),
        migrations.AlterField(
            model_name='info',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='info',
            name='ubicacion',
            field=models.CharField(default='', max_length=100, verbose_name='Ubicacion'),
        ),
    ]
