# Generated by Django 3.2.16 on 2022-12-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221215_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '05- About'},
        ),
        migrations.AlterModelOptions(
            name='carrusel1',
            options={'verbose_name': 'elemento', 'verbose_name_plural': '02- Carrusel'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': '10- Contáctenos'},
        ),
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': '14- Contactos'},
        ),
        migrations.AlterModelOptions(
            name='destinatario',
            options={'verbose_name': '13- Destinatario'},
        ),
        migrations.AlterModelOptions(
            name='fruit',
            options={'verbose_name': 'fruta', 'verbose_name_plural': '07- Frutas'},
        ),
        migrations.AlterModelOptions(
            name='fruittitle',
            options={'verbose_name': '06- Título para frutas'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '12- Información'},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': '03- Barra de navehación'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '04- Shop'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'testimonio', 'verbose_name_plural': '09- Testimonios'},
        ),
        migrations.AlterModelOptions(
            name='testimonialtitle',
            options={'verbose_name': '08- Título testimonio'},
        ),
        migrations.AlterModelOptions(
            name='titulo',
            options={'verbose_name': '01- Titulo'},
        ),
        migrations.AddField(
            model_name='testimonial',
            name='enunciado',
            field=models.CharField(default='', max_length=50, verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='about',
            name='descripcion',
            field=models.TextField(default='There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour', max_length=2000, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='mapa',
            field=models.TextField(default='', max_length=1000, verbose_name='Mapa'),
        ),
    ]
