# Generated by Django 3.2.16 on 2022-12-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20221219_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titulo',
            options={'verbose_name': '01- Encabezado'},
        ),
        migrations.AddField(
            model_name='titulo',
            name='imagen1',
            field=models.ImageField(default=23, upload_to='images/header_imagen/', verbose_name='Imagen'),
            preserve_default=False,
        ),
    ]
