# Generated by Django 3.2.16 on 2022-12-23 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20221222_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titulo',
            name='imagen1',
        ),
        migrations.AddField(
            model_name='titulo',
            name='imagen',
            field=models.ImageField(default=' ', upload_to='images/header_imagen/', verbose_name='Imagen'),
        ),
    ]
