# Generated by Django 3.2.16 on 2022-12-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221222_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='email_en',
            field=models.EmailField(default='', max_length=100, verbose_name='Enlace de mail'),
        ),
        migrations.AddField(
            model_name='info',
            name='telef_en',
            field=models.CharField(default='', max_length=100, verbose_name='Enlace de teléfono'),
        ),
        migrations.AddField(
            model_name='info',
            name='ubicacion_en',
            field=models.CharField(default='', max_length=100, verbose_name='Enlace de ubicacion'),
        ),
        migrations.AlterField(
            model_name='info',
            name='telef',
            field=models.CharField(default='', max_length=100, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='imagen',
            field=models.ImageField(default=' ', upload_to='images/header_imagen/', verbose_name='Imagen de encabezado'),
        ),
    ]
