# Generated by Django 3.2.16 on 2022-12-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20221223_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email_en',
            field=models.TextField(default='', max_length=100, verbose_name='Enlace de mail'),
        ),
    ]
