# Generated by Django 3.2.16 on 2022-12-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_info_email_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email_en',
            field=models.CharField(default='', max_length=100, verbose_name='Enlace de mail'),
        ),
    ]
