# Generated by Django 3.2.16 on 2022-12-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_info_email_en'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '05- Sobre nosotros'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': '04- Tienda'},
        ),
        migrations.AddField(
            model_name='info',
            name='linkeaadin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testimonialtitle',
            name='titulo',
            field=models.CharField(default='What Syas Cutomer', max_length=100, verbose_name='Título'),
        ),
    ]
