# Generated by Django 3.2.16 on 2022-12-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20221226_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='linkeaadin',
        ),
        migrations.AddField(
            model_name='info',
            name='facebookAct',
            field=models.BooleanField(default=False, verbose_name='Activar facebook'),
        ),
        migrations.AddField(
            model_name='info',
            name='instagramAct',
            field=models.BooleanField(default=False, verbose_name='Activar instagram'),
        ),
        migrations.AddField(
            model_name='info',
            name='linkedinAct',
            field=models.BooleanField(default=False, verbose_name='Activar linkedin'),
        ),
        migrations.AddField(
            model_name='info',
            name='twitterAct',
            field=models.BooleanField(default=False, verbose_name='Activar twitter'),
        ),
    ]
