# Generated by Django 3.2.16 on 2022-12-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20221226_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='imagen',
            field=models.ImageField(upload_to='images/shop/', verbose_name='Imagen'),
        ),
    ]
