# Generated by Django 3.2.16 on 2022-12-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_shop_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='imagen',
            field=models.ImageField(upload_to='images/client/', verbose_name='Imagen'),
        ),
    ]
