# Generated by Django 3.2.16 on 2023-01-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_testimonial_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': '14- Subscripciones',
            },
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={'verbose_name': '03- Barra de navegación'},
        ),
    ]
