# Generated by Django 3.2.16 on 2023-01-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230105_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscripciones',
            options={'verbose_name': 'Subscripción', 'verbose_name_plural': '15- Subscripciones'},
        ),
    ]
