# Generated by Django 3.2.16 on 2023-01-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_subscripciones_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='activ',
            field=models.BooleanField(default=True),
        ),
    ]
